#!/bin/bash
DOCKER_TTY_OPTS=-i
if [ -t 0 ]; then
    DOCKER_TTY_OPTS=-it
fi
ssh_opts=
if [ -n "$SSH_AUTH_SOCK" ]; then
    ssh_opts="-e SSH_AUTH_SOCK=/ssh-agent -v $SSH_AUTH_SOCK:/ssh-agent"
fi

ROOTFS_DIR="/rootfs/wheezy-armel"
TARGET_ARCH="armel"
case "$1" in
    --target)
        shift
        case "$1" in
            wheezy-armhf)
                ROOTFS_DIR="/rootfs/$1"
                TARGET_ARCH="armhf"
                shift
                ;;
            wheezy-armel)
                ROOTFS_DIR="/rootfs/$1"
                TARGET_ARCH="armel"
                shift
                ;;
            jessie-armel|jessie-armhf)
                echo "Jessie is not implemented yet"
                exit 1
                ;;
            *)
                echo "Unknown target: $1"
                exit 1
                ;;
        esac
        ;;
    *)
        echo "Warning: -target option is missing"
        ;;
esac

IMAGE=${IMAGE:-contactless/devenv}
docker run $DOCKER_TTY_OPTS --privileged --rm \
       -e DEV_UID=$UID \
       -e DEV_USER=$USER \
       -e DEV_DIR="$PWD" \
       -e DEV_TERM="$TERM" \
       -e ROOTFS_DIR="$ROOTFS_DIR" \
       -e TARGET_ARCH="$TARGET_ARCH" \
       -v $HOME:$HOME \
       $ssh_opts \
       -h wbdevenv \
       $IMAGE \
       "$@"
