#!/bin/bash
DOCKER_TTY_OPTS=-i
if [ -t 0 ]; then
    DOCKER_TTY_OPTS=-it
fi
ssh_opts=
if [ -n "$SSH_AUTH_SOCK" ]; then
    ssh_opts="-e SSH_AUTH_SOCK=/ssh-agent -v $SSH_AUTH_SOCK:/ssh-agent"
fi
ROOTFS="/rootfs/wheezy-armel"
TARGET_ARCH="armel"

case "$WBDEV_TARGET" in
wheezy-armhf)
    ROOTFS="/rootfs/wheezy-armhf"
    TARGET_ARCH="armhf"
    ;;
wheezy-armel)
    ROOTFS="/rootfs/wheezy-armel"
    TARGET_ARCH="armel"
    ;;
stretch-armhf)
    ROOTFS="/rootfs/stretch-armhf"
    TARGET_ARCH="armhf"
    ;;
stretch-armel)
    ROOTFS="/rootfs/stretch-armel"
    TARGET_ARCH="armel"
    ;;
*)
    echo "Warning: WBDEV_TARGET is not set, defaulting to wheezy-armel"
    ;;
esac

IMAGE=${WBDEV_IMAGE:-contactless/devenv}

if [[ $OSTYPE == darwin* ]]
then
	VM_HOME="/home/$USER"
else
	VM_HOME=$HOME
fi

PREFIX="$VM_HOME/wbdev/go/src/github.com/contactless"

INSTALL_DEPS=${WBDEV_INSTALL_DEPS:-no}

docker run $DOCKER_TTY_OPTS --privileged \
       -e DEV_UID=$UID \
       -e DEV_USER=$USER \
       -e DEV_DIR="$PREFIX/${PWD##*/}" \
       -e DEV_TERM="$TERM" \
       -e ROOTFS="$ROOTFS" \
       -e TARGET_ARCH="$TARGET_ARCH" \
       -e INSTALL_DEPS="$INSTALL_DEPS" \
       -v $HOME:$VM_HOME \
       -v ${PWD%/*}:$PREFIX \
       $ssh_opts \
       -h wbdevenv \
       $IMAGE \
       "$@"
