#!/bin/sh
# prerm script for mosquitto
#
# see: dh_installdeb(1)

set -e

case "$1" in
	remove|purge|deconfigure)
		if [ -x /etc/init.d/mosquitto ]; then
			if [ -x /usr/sbin/invoke-rc.d ]; then
				invoke-rc.d mosquitto stop
			else
				/etc/init.d/mosquitto stop
			fi
		fi
	;;

	upgrade)
	;;
	failed-upgrade)
	;;

	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
