#!/bin/bash

PREFIX="00:86"

. /etc/wb_env.sh

function debug() {
    echo $1 1>&2
}

function _gen_mac_simcom()
{
    IMEI=`wb-gsm imei`
    RC=$?

    IMEI_SN=`echo $IMEI | cut -c 9-14`

    if [[ $RC != 0 ]] ; then
        debug "ERROR"
        return $RC;
    fi
    IMEIPREFIX=${IMEI:0:8}

    MAC_PREFIX_OCTET=`printf "%x\n" $((IMEIPREFIX%256))`

    MAC="$PREFIX:${MAC_PREFIX_OCTET}:${IMEI_SN:0:2}:${IMEI_SN:2:2}:${IMEI_SN:4:2}"
    echo $MAC
    return 0
}

function gen_mac_simcom()
{
    debug "Trying to get GSM IMEI..."
    wb-gsm restart_if_broken
    _gen_mac_simcom
    RC=$?
    if [[ $RC != 0 ]] ; then
        wb-gsm restart_if_broken
        RC=$?
    fi

    return $RC
}

function gen_mac_wifi()
{
    debug "Trying to get Wi-Fi MAC..."
    ADDR_FNAME=/sys/class/net/wlan0/address
    if [ -e $ADDR_FNAME ]; then
        WIFI_MAC=`cat $ADDR_FNAME`
        MAC="$PREFIX:41:${WIFI_MAC:9:8}"
        echo $MAC
        return 0
    else
        return 1;
    fi
}

function gen_mac_cpu()
{
    debug "Trying to generate MAC from CPU serial..."
    SERIAL_STR=`cat /proc/cpuinfo | grep Serial | cut -d':' -f2 | cut -c2-`
    RC=$?
    if [[ $RC != 0 ]] ; then
        debug "Error reading serial from /proc/cpuinfo"
        return 1;
    fi;


    debug "Got SoC serial: ${SERIAL_STR}"

    if [[ "${SERIAL_STR}" = "0000000000000000" ]] ; then
        debug "SoC serial is empty, ignoring. Unsupported SoC or maybe old kernel?"
        return 1;
    fi;

    SERIAL_MD5=`echo ${SERIAL_STR} | md5sum | cut -d' ' -f1`

    MAC="$PREFIX:44:${SERIAL_MD5:0:2}:${SERIAL_MD5:2:2}:${SERIAL_MD5:4:2}"
    echo $MAC
    return 0
}

function gen_mac_rand()
{
    debug "Trying to get random MAC..."
    LC_CTYPE=C
    SUFFIX=
    for i in {1..3}
    do
        IFS= read -d '' -r -n 1 char < /dev/urandom
        SUFFIX+=$(printf -- ':%02x\n' "'$char")
    done
    MAC="$PREFIX:43$SUFFIX"
    echo $MAC
    return 0;
}

function gen_mac_best()
{
    gen_mac_wifi || gen_mac_cpu || gen_mac_simcom || gen_mac_rand
}

case "$1" in
	"cpu" )
		gen_mac_cpu
	;;
	"gsm" )
		gen_mac_simcom
	;;
	"wifi" )
		gen_mac_wifi
	;;
	"rand" )
		gen_mac_rand
	;;

    "-h" | "--help" | "help" )
		echo "USAGE: $0 [gsm|cpu|wifi|rand|help]";
        exit 0;
    ;;
	* )
		gen_mac_best
	;;
esac

