#!/bin/bash

. /usr/lib/wb-gsm-common.sh

gsm_init

case "$1" in
    "reset" )
        reset
    ;;

    "toggle" )
        toggle
    ;;

    "on" )
        ensure_on
    ;;

    "restart_if_broken" )
        restart_if_broken
    ;;

    "off" )
        switch_off
    ;;

    "set_speed" )
        set_speed
    ;;
    "init_baud" )
        init_baud
    ;;

    "imei" )
        imei
    ;;

    "imei_sn" )
        imei_sn
    ;;

    * )
        echo "USAGE: $0 reset|toggle|on|restart_if_broken|off|set_speed|init_baud|imei|imei_sn";
    ;;
esac




