#!/bin/sh
# postinst script for mosquitto
#
# see: dh_installdeb(1)

set -e

setup_mosquitto_user() {
	if ! getent passwd mosquitto >/dev/null; then
		adduser --quiet --system --no-create-home --home /var/lib/mosquitto --shell /usr/sbin/nologin mosquitto
	fi
}

fix_permissions() {
	chown mosquitto /var/lib/mosquitto
}

case "$1" in
	configure)
		setup_mosquitto_user
		fix_permissions
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac


# Automatically added by dh_installinit
if [ -x "/etc/init.d/mosquitto" ]; then
	update-rc.d mosquitto defaults >/dev/null
	invoke-rc.d mosquitto start || exit $?
fi
# End automatically added section


exit 0
