#!/bin/sh
update-rc.d wb-prepare start 10 S

invoke-rc.d wb-prepare fix_macs

update-rc.d wb-gsm-rtc defaults
invoke-rc.d wb-gsm-rtc start

update-rc.d wb-init defaults
invoke-rc.d wb-init start

[ -e /var/www/uploads ] || mkdir -p /var/www/uploads
chown www-data:www-data /var/www/uploads
update-rc.d wb-watch-update defaults
invoke-rc.d wb-watch-update start
